# Generated by Django 6.0.3 on 2026-04-21 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0002_cateringpackage_cateringbooking_event_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cateringpackage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='packages/'),
        ),
    ]
